package com.example.recyclerview

object Constants {
    val professores = arrayOf(
        Professor("José Augusto Suruagy Monteiro", "suruagy"),
        Professor("Veronica Teichrieb", "vt"),
        Professor("Pedro Machado Manhães de Castro", "pmmc"),
        Professor("Paulo Gustavo Soares Fonseca", "paguso"),
        Professor("Paulo André da Silva Gonçalves", "pasg"),
        Professor("Márcio Lopes Cornélio", "mlc2"),
        Professor("Leopoldo Motta Teixeira", "lmt"),
        Professor("Kiev Santos da Gama", "kiev"),
        Professor("Jaelson Freire Brelaz de Castro", "jbc"),
        Professor("Filipe Carlos de Albuquerque Calegário ", "calegario"),
        Professor("Giordano Ribeiro Eulalio Cabral", "grec"),
        Professor("Cristiano Coelho de Araújo", "cca2"),
        Professor("Adriano Augusto de Moraes Sarmento", "aams"),
        Professor("Vinicius Cardoso Garcia", "vcg"),
        Professor("Sérgio Castelo Branco Soares", "scbs"),
        Professor("Silvio de Barros Melo", "sbm"),
        Professor("Ricardo Bastos Cavalcante Prudêncio", "rbcp"),
        Professor("Renata Maria Cardoso Rodrigues de Souza", "rmcrs"),
        Professor("Juliano Manabu Iyoda", "jmi"),
        Professor("Marcelo d'Amorim", "damorim"),
        Professor("Germano Crispim Vasconcelos", "gcv"),
        Professor("George Darmiton da Cunha Cavalcanti", "gdcc"),
        Professor("Geber Lisboa Ramalho", "glr"),
        Professor("Fernando José Castor de Lima Filho", "castor"),
        Professor("Cleber Zanchettin", "cz"),
        Professor("Alex Sandro Gomes", "asg"),
        Professor("Teresa Bernarda Ludermir", "tbl"),
        Professor("Ruy José Guerra Barretto de Queiroz", "ruy"),
        Professor("Paulo Henrique Monteiro Borba", "phmb"),
    )
}
